import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../sass/Home.module.scss'

// Importação da interface do post ( contrato )
import PostCard, { IPost } from '../components/post-card/postCard'


const Home: NextPage = () => {

  // Estado que guarda o array de posts da página
  const [posts, setPosts] = useState<IPost[]>([]);


  /**
   * Esse useEffect deve ser executado em primeiro lugar no 
   * momento de Hydration da página. Ele, até o momento é
   * inteiramente responsável por ler os dados da API 
   */
  useEffect(() => {
    fetch('https://jsonplaceholder.typicode.com/posts')
      .then(response => response.json())
      .then(data => {
        setPosts(data);
      }).catch((err) => {
        /**
         * Em caso de erro é disparadas essa exceção no terminal
         */
        console.error('Falha ao buscar dados da api')
      });
  }, []);



  return (
    <div className={styles.container}>
      <Head>
        <title>Teste de front-end</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
          BLOG
        </h1>
        <h3>Teste de front-end e consumo de API</h3>
        <section className={styles.postsWrapper}>

          {
            posts.map((item, key) => {
              return (
                <PostCard {...item} key={key} />
              );
            })
          }
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://gabrielvictor.web.app"
          target="_blank"
        >
          Desenvolvido por Gabriel Victor
        </a>
      </footer>
    </div>
  )
}

export default Home
